### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by kotyara12** [knky-ru/Yandex-Zen-Parser#1]
```
G:\dzen>python.exe ZenParser.py
Successfully created the directory output
Start processing URL: https://dzen.ru/......
Successfully created the directory output/......
Traceback (most recent call last):
  File "G:\dzen\ZenParser.py", line 14, in <module>
    Parser.parseToHtml(loadURLsFromJson())
  File "G:\dzen\KNKY_ZenParser.py", line 119, in parseToHtml
    html_p_list = parseHtml(soup)
  File "G:\dzen\KNKY_ZenParser.py", line 17, in parseHtml
    html_p_list = html_body.find_all(SEEK_ATTRIBUTES)
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by altynbek07** [comment]
Same
